# Generated by Django 3.0.7 on 2020-12-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0031_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='email',
            field=models.TextField(),
        ),
    ]
