# Generated by Django 3.0.7 on 2020-12-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0032_auto_20201223_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='min_time',
            field=models.IntegerField(default=0, verbose_name='Time in minutes for Exercise'),
        ),
    ]
