# Generated by Django 3.0.7 on 2020-12-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0033_auto_20201224_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='negative_weightage',
            field=models.FloatField(default=100, help_text='Will be considered as Negative percentage'),
        ),
    ]
