# Generated by Django 3.0.7 on 2020-12-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaksh', '0034_quiz_negative_weightage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='negative_weightage',
            field=models.FloatField(default=100, help_text='Will be considered as Negative percentage per question'),
        ),
    ]
